### ISSUE TITLE
[Suggestion] Tablist TPS

### ISSUE THREAD

**Issue by RedCrafter07** [SurvivalAttack/Survival-Attack-7#1]
**Is your feature request related to a problem? Please describe.**
Yes, low TPS.

**Describe the solution you'd like**
I want MrSilly to add the mod which shows TPS in the tablist.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by MrSilly07** [comment]
accepted

**Comment by fireheart3911** [comment]
Will be added in 1.1.0
