### ISSUE TITLE
Breaking Blocks in claimed chunks (not mine)

### ISSUE THREAD

**Issue by tigerfell1** [SurvivalAttack/Survival-Attack-7#7]
You have to place a chest (could also be an energy cable or sth that isnt a whole block), using a slingshot form supplementaries, next to the block which you want to destroy. Then you have to shift + right click a water sigil (lava sigil works as well) on the side of the chest where the block which you want to destroy is. After that the block is replaced (drops items) by water (or lava) and you can simply remove it using a void sigil (all uses of a sigil require blood in your soul network as otherwise you will take damage). After that you simply use the water sigil on the surface where you placed your chest (or sth else; has to be in the same block). Then you remove the water (or lava) with a void sigil.

**Comment by fireheart3911** [comment]
Can confirm in V1.0.4

**Comment by fireheart3911** [comment]
Closed as season ended
